
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author PRAKASH
 */
public class books extends javax.swing.JFrame {

    /**
     * Creates new form books
     */
    public books() {
        initComponents();
    }
     DefaultTableModel model=new DefaultTableModel();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        txtdqty = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        chk1 = new javax.swing.JCheckBox();
        chk2 = new javax.swing.JCheckBox();
        chk3 = new javax.swing.JCheckBox();
        chk4 = new javax.swing.JCheckBox();
        chk5 = new javax.swing.JCheckBox();
        txtsum = new javax.swing.JComboBox<>();
        txtsum1 = new javax.swing.JComboBox<>();
        txtsum2 = new javax.swing.JComboBox<>();
        txtsum3 = new javax.swing.JComboBox<>();
        txtsum4 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtbill = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        txtsqty = new javax.swing.JTextField();
        txtsqty2 = new javax.swing.JTextField();
        txtsqty3 = new javax.swing.JTextField();
        txtsqty4 = new javax.swing.JTextField();
        txtsqty1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtdqty.setBackground(new java.awt.Color(0, 204, 102));
        txtdqty.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 204));
        jLabel1.setText("BOOKS");
        txtdqty.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 174, 71));

        chk1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        chk1.setText("Web Technology");
        txtdqty.add(chk1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 98, 175, -1));

        chk2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        chk2.setText("Database  Management");
        txtdqty.add(chk2, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 164, -1, -1));

        chk3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        chk3.setText("Java Programming");
        txtdqty.add(chk3, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 241, -1, -1));

        chk4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        chk4.setText("Computer Networks");
        txtdqty.add(chk4, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 327, -1, -1));

        chk5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        chk5.setText("C Programming");
        txtdqty.add(chk5, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 403, -1, -1));

        txtsum.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtsum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Local Author", "Foreign Author", " " }));
        txtdqty.add(txtsum, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 98, -1, -1));

        txtsum1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtsum1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Local Author", "Foreign Author", " " }));
        txtsum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsum1ActionPerformed(evt);
            }
        });
        txtdqty.add(txtsum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 167, -1, -1));

        txtsum2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtsum2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Local Author", "Foreign Author", " " }));
        txtdqty.add(txtsum2, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 244, -1, -1));

        txtsum3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtsum3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Local Author", "Foreign Author", " " }));
        txtdqty.add(txtsum3, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 316, -1, -1));

        txtsum4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtsum4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Local Author", "Foreign Author", " " }));
        txtdqty.add(txtsum4, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 406, -1, -1));

        jt.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book", "Price", "Qty", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jt);

        txtdqty.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 89, 435, 356));

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        txtdqty.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 486, 59, -1));

        jLabel2.setBackground(new java.awt.Color(255, 0, 255));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 255));
        jLabel2.setText("TOTAL AMOUNT");
        txtdqty.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(596, 489, -1, -1));

        txtbill.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txtbill.setText("Total");
        txtdqty.add(txtbill, new org.netbeans.lib.awtextra.AbsoluteConstraints(767, 484, -1, -1));

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton2.setText("PAY");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        txtdqty.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(886, 486, -1, -1));
        txtdqty.add(txtsqty, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 98, 91, -1));
        txtdqty.add(txtsqty2, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 244, 91, -1));
        txtdqty.add(txtsqty3, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 327, 91, -1));
        txtdqty.add(txtsqty4, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 406, 91, -1));
        txtdqty.add(txtsqty1, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 175, 91, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bookstore.jpg"))); // NOI18N
        txtdqty.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 570));

        jLabel4.setText("jLabel4");
        txtdqty.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, 80, -1));

        jTextField1.setText("jTextField1");
        txtdqty.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtdqty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtdqty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtsum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsum1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsum1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        double sum = 0;
        double price;
        double qty;
        double cal = 0;
        
         if(chk1.isSelected())
        {
           String WebTechnology = chk1.getText();
           String mes= txtsum.getSelectedItem().toString();
            price = 140.0;
            qty = Integer.parseInt(txtsqty.getText());
        
            
            
            
             if(mes.equals('1'))
             {
                 cal = (qty * price) ;
                 model = (DefaultTableModel)jt.getModel();
                 model.addRow(new Object[]
                 {
                     WebTechnology,
                     price,
                     qty,
                     cal
                 });
                 
                 
                 
             }
             else
             {
                 cal = (qty * price) ;
                 
                 model = (DefaultTableModel)jt.getModel();
                 
                 model.addRow(new Object[]
                 {
                     
                     WebTechnology,
                     price,
                     qty,
                     cal
                 })  ;
                 
                 
                          
             }
    }//GEN-LAST:event_jButton1ActionPerformed
if(chk2.isSelected())
        {
           String DatabaseManagement= chk2.getText();
           String mes1= txtsum1.getSelectedItem().toString();
            price = 200.0;
            qty = Integer.parseInt(txtsqty1.getText());
        
            
            
            
             if(mes1.equals('1'))
             {
                 cal = (qty * price) ;
                 model = (DefaultTableModel)jt.getModel();
                 model.addRow(new Object[]
                 {
                     DatabaseManagement,
                     price,
                     qty,
                     cal
                 });
                 
                 
                 
             }
             else
             {
                 cal = (qty * price) ;
                 
                 model = (DefaultTableModel)jt.getModel();
                 
                 model.addRow(new Object[]
                 {
                     
                     DatabaseManagement,
                     price,
                     qty,
                     cal,
                 })  ;
                 
                 
                          
             
    }           }                             
       
    
             if(chk3.isSelected())
        {
           String Javaprogramming= chk3.getText();
           String mes2= txtsum2.getSelectedItem().toString();
            price = 230.0;
            qty = Integer.parseInt(txtsqty2.getText());
        
            
            
            
             if(mes2.equals('1'))
             {
                 cal = (qty * price) ;
                 model = (DefaultTableModel)jt.getModel();
                 model.addRow(new Object[]
                 {
                     Javaprogramming,
                     price,
                     qty,
                     cal
                 });
                 
                 
                 
             }
             else
             {
                 cal = (qty * price) ;
                 
                 model = (DefaultTableModel)jt.getModel();
                 
                 model.addRow(new Object[]
                 {
                     
                     Javaprogramming,
                     price,
                     qty,
                     cal,
                 })  ;
                 
                 
                          
             
    } }
               if(chk4.isSelected())
        {
           String Computernetworks= chk4.getText();
           String mes3= txtsum3.getSelectedItem().toString();
            price = 350.0;
            qty = Integer.parseInt(txtsqty3.getText());
        
            
            
            
             if(mes3.equals('1'))
             {
                 cal = (qty * price) ;
                 model = (DefaultTableModel)jt.getModel();
                 model.addRow(new Object[]
                 {
                     Computernetworks,
                     price,
                     qty,
                     cal
                 });
                 
                 
                 
             }
             else
             {
                 cal = (qty * price) ;
                 
                 model = (DefaultTableModel)jt.getModel();
                 
                 model.addRow(new Object[]
                 {
                     
                   Computernetworks,
                     price,
                     qty,
                     cal,
                 })  ;
                 
                 
                          
             
    }  }   
               if(chk5.isSelected())
        {
           String Cprogramming= chk5.getText();
           String mes4= txtsum4.getSelectedItem().toString();
            price = 360.0;
            qty = Integer.parseInt(txtsqty4.getText());
        
             if(mes4.equals('1'))
             {
                 cal = (qty * price) ;
                 model = (DefaultTableModel)jt.getModel();
                 model.addRow(new Object[]
                 {
                     Cprogramming,
                     price,
                     qty,
                     cal
                 });
                 
                 
                 
             }
             else
             {
                 cal = (qty * price) ;
                 
                 model = (DefaultTableModel)jt.getModel();
                 
                 model.addRow(new Object[]
                 {
                     
                   Cprogramming,
                     price,
                     qty,
                     cal,
                 })  ;
                 
                 
                          
             
    }  }                                      
    
      for(double i=0; i <jt.getRowCount(); i++)
        {
            sum = sum + Double.parseDouble(jt.getValueAt((int) i, 3).toString());
        
        
        txtbill.setText(Double.toString(sum));
        }}
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new Payment().setVisible(true);
       
    }//GEN-LAST:event_jButton2ActionPerformed

               
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new books().setVisible(true);
            }
        });
    
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JCheckBox chk1;
    private javax.swing.JCheckBox chk2;
    private javax.swing.JCheckBox chk3;
    private javax.swing.JCheckBox chk4;
    private javax.swing.JCheckBox chk5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable jt;
    private javax.swing.JLabel txtbill;
    private javax.swing.JPanel txtdqty;
    private javax.swing.JTextField txtsqty;
    private javax.swing.JTextField txtsqty1;
    private javax.swing.JTextField txtsqty2;
    private javax.swing.JTextField txtsqty3;
    private javax.swing.JTextField txtsqty4;
    private javax.swing.JComboBox<String> txtsum;
    private javax.swing.JComboBox<String> txtsum1;
    private javax.swing.JComboBox<String> txtsum2;
    private javax.swing.JComboBox<String> txtsum3;
    private javax.swing.JComboBox<String> txtsum4;
    // End of variables declaration//GEN-END:variables
}
