


import javax.swing.table.DefaultTableModel;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author PRAKASH
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }
    DefaultTableModel model=new DefaultTableModel();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        chk2 = new javax.swing.JCheckBox();
        chk3 = new javax.swing.JCheckBox();
        chk4 = new javax.swing.JCheckBox();
        chk5 = new javax.swing.JCheckBox();
        txtsqty = new javax.swing.JTextField();
        txtqty = new javax.swing.JTextField();
        txtrqty = new javax.swing.JTextField();
        txtfqty = new javax.swing.JTextField();
        txtdqty = new javax.swing.JTextField();
        txtsum = new javax.swing.JComboBox<>();
        txtstut = new javax.swing.JComboBox<>();
        txtflum = new javax.swing.JComboBox<>();
        txtricm = new javax.swing.JComboBox<>();
        txtdham = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        txtbill = new javax.swing.JLabel();
        chk1 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(51, 51, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 204));
        jLabel1.setText("Foods");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 140, -1));

        chk2.setBackground(new java.awt.Color(255, 255, 255));
        chk2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        chk2.setForeground(new java.awt.Color(255, 255, 255));
        chk2.setText("Tea");
        getContentPane().add(chk2, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 185, 80, -1));

        chk3.setBackground(new java.awt.Color(255, 255, 255));
        chk3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        chk3.setForeground(new java.awt.Color(255, 255, 255));
        chk3.setText("Rice");
        getContentPane().add(chk3, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 234, 80, -1));

        chk4.setBackground(new java.awt.Color(255, 255, 255));
        chk4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        chk4.setForeground(new java.awt.Color(255, 255, 255));
        chk4.setText("Flour");
        getContentPane().add(chk4, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 297, 80, -1));

        chk5.setBackground(new java.awt.Color(255, 255, 255));
        chk5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        chk5.setForeground(new java.awt.Color(255, 255, 255));
        chk5.setText("Dhall");
        getContentPane().add(chk5, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 357, 80, -1));

        txtsqty.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtsqty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsqtyActionPerformed(evt);
            }
        });
        getContentPane().add(txtsqty, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 122, 169, -1));

        txtqty.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txtqty, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 184, 169, -1));

        txtrqty.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txtrqty, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 233, 169, -1));

        txtfqty.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txtfqty, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 296, 169, -1));

        txtdqty.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txtdqty, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 356, 169, -1));

        txtsum.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtsum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "KG", "GR" }));
        getContentPane().add(txtsum, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 122, -1, -1));

        txtstut.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtstut.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "KG", "GR" }));
        getContentPane().add(txtstut, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 184, -1, -1));

        txtflum.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtflum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "KG", "GR" }));
        getContentPane().add(txtflum, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 233, -1, -1));

        txtricm.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtricm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "KG", "GR" }));
        txtricm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtricmActionPerformed(evt);
            }
        });
        getContentPane().add(txtricm, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 296, -1, -1));

        txtdham.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtdham.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "KG", "GR" }));
        getContentPane().add(txtdham, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 356, -1, -1));

        jt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Price", "Qty", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jt);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 424, 284));

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 439, 72, -1));

        txtbill.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtbill.setForeground(new java.awt.Color(255, 255, 255));
        txtbill.setText("Total");
        getContentPane().add(txtbill, new org.netbeans.lib.awtextra.AbsoluteConstraints(678, 451, -1, -1));

        chk1.setBackground(new java.awt.Color(255, 255, 255));
        chk1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        chk1.setForeground(new java.awt.Color(255, 255, 255));
        chk1.setText("Sugar");
        getContentPane().add(chk1, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 123, 80, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Total Amount");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(532, 451, -1, -1));

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton2.setText("Pay");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 448, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foodbg.jpeg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1040, 10, 1920, 600));

        jCheckBox2.setText("jCheckBox2");
        getContentPane().add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Salt");
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        jCheckBox3.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox3.setText("jCheckBox3");
        getContentPane().add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtricmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtricmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtricmActionPerformed

    private void txtsqtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsqtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsqtyActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
  double sum = 0;
        double price;
        double qty;
        double cal = 0;
        
         if(chk1.isSelected())
        {
           String suger = chk1.getText();
           String mes= txtsum.getSelectedItem().toString();
            price = 140.0;
            qty = Integer.parseInt(txtsqty.getText());
            
             if(mes.equals("KG"))
                  {
                cal = (qty * price) ;
                model = (DefaultTableModel)jt.getModel();
                model.addRow(new Object[]
                {  
                suger,
                 price,
                 qty,
                 cal
                });  
          }
             else
             {
              cal = (qty/1000 * price) ;
 
              model = (DefaultTableModel)jt.getModel();
            
            model.addRow(new Object[]
            {
            
            suger,
             price,       
              qty,
             cal
            });        
             }}
         if(chk2.isSelected())
        {
            String tea = chk2.getText();
           String mes1= txtstut.getSelectedItem().toString();
            price = 200.0;
            qty = Integer.parseInt(txtqty.getText());
            
             if(mes1.equals("KG"))
          {
               cal = (qty * price) ;
               model = (DefaultTableModel)jt.getModel();
               model.addRow(new Object[]
                {  
                tea,
                 price,
                 qty,
                 cal
                });  
                }
             else
             {
              cal = (qty/1000 * price) ;
 
              model = (DefaultTableModel)jt.getModel();          
              model.addRow(new Object[]
            {
            
             tea,
             price,
             qty,
             cal
            });        
             }
              }
            if(chk3.isSelected())
        {
            String flour = chk3.getText();
           String mes2= txtflum.getSelectedItem().toString();
            price = 250.0;
            qty = Integer.parseInt(txtfqty.getText());
            
             if(mes2.equals("KG"))
          {
               cal = (qty * price) ;
               model = (DefaultTableModel)jt.getModel();
               model.addRow(new Object[]
                {  
                flour,
                 price,
                 qty,
                 cal
                });  
                 }
             else
             {
              cal = (qty/1000 * price) ;
           
              model = (DefaultTableModel)jt.getModel();          
              model.addRow(new Object[]
            {
            
             flour,
             price,
             qty,
             cal
            });        
             }
              }
           if(chk4.isSelected())
        {
            String rice = chk4.getText();
           String mes3= txtricm.getSelectedItem().toString();
            price = 250.0;
            qty = Integer.parseInt(txtrqty.getText());
            
             if(mes3.equals("KG"))
          {
               cal = (qty * price) ;
               model = (DefaultTableModel)jt.getModel();
               model.addRow(new Object[]
                        {  
                rice,
                 price,
                 qty,
                 cal
                });  
          }
             else
             {
              cal = (qty/1000 * price) ;
 
              model = (DefaultTableModel)jt.getModel();          
              model.addRow(new Object[]
            {
            
             rice,
                   price,
             qty,
             cal
            });        
             }
            
        }
          if(chk5.isSelected())
        {
            String dhall = chk5.getText();
           String mes4= txtdham.getSelectedItem().toString();
            price = 350.0;
            qty = Integer.parseInt(txtdqty.getText());
            
             if(mes4.equals("KG"))
          {
               cal = (qty * price) ;
               model = (DefaultTableModel)jt.getModel();
               model.addRow(new Object[]
                {  
                dhall,
                 price,
                 qty,
                 cal
                });  
                }
             else
             {
              cal = (qty/1000 * price) ;
 
              model = (DefaultTableModel)jt.getModel();          
              model.addRow(new Object[]
            {
            
             dhall,
             price,
             qty,
             cal
            });        
             }
             
           for(double i=0; i <jt.getRowCount(); i++)
        {
            sum = sum + Double.parseDouble(jt.getValueAt((int) i, 3).toString());
        }
        
        txtbill.setText(Double.toString(sum));
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new Payment().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new NewJFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chk1;
    private javax.swing.JCheckBox chk2;
    private javax.swing.JCheckBox chk3;
    private javax.swing.JCheckBox chk4;
    private javax.swing.JCheckBox chk5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jt;
    private javax.swing.JLabel txtbill;
    private javax.swing.JComboBox<String> txtdham;
    private javax.swing.JTextField txtdqty;
    private javax.swing.JComboBox<String> txtflum;
    private javax.swing.JTextField txtfqty;
    private javax.swing.JTextField txtqty;
    private javax.swing.JComboBox<String> txtricm;
    private javax.swing.JTextField txtrqty;
    private javax.swing.JTextField txtsqty;
    private javax.swing.JComboBox<String> txtstut;
    private javax.swing.JComboBox<String> txtsum;
    // End of variables declaration//GEN-END:variables
}
