
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author PRAKASH
 */
public class stationary extends javax.swing.JFrame {

    /**
     * Creates new form stationary
     */
    public stationary() {
        initComponents();}
         DefaultTableModel model=new DefaultTableModel();

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        chk1 = new javax.swing.JCheckBox();
        chk2 = new javax.swing.JCheckBox();
        chk3 = new javax.swing.JCheckBox();
        txt1 = new javax.swing.JTextField();
        txt2 = new javax.swing.JTextField();
        txt3 = new javax.swing.JTextField();
        chk5 = new javax.swing.JCheckBox();
        chk6 = new javax.swing.JCheckBox();
        chk7 = new javax.swing.JCheckBox();
        txt5 = new javax.swing.JTextField();
        txt6 = new javax.swing.JTextField();
        txt7 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtable = new javax.swing.JTable();
        chk4 = new javax.swing.JCheckBox();
        txt4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtbill = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setText("STATIONERY");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, -1, -1));

        chk1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        chk1.setText("Pencil");
        jPanel1.add(chk1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        chk2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        chk2.setText("Pen");
        chk2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk2ActionPerformed(evt);
            }
        });
        jPanel1.add(chk2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        chk3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        chk3.setText("Eraser");
        chk3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk3ActionPerformed(evt);
            }
        });
        jPanel1.add(chk3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        txt1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 99, -1));

        txt2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 99, -1));

        txt3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(txt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 99, -1));

        chk5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        chk5.setText("Sharpner");
        jPanel1.add(chk5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, 28));

        chk6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        chk6.setText("Chart");
        jPanel1.add(chk6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        chk7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        chk7.setText("Note");
        chk7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk7ActionPerformed(evt);
            }
        });
        jPanel1.add(chk7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        txt5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt5ActionPerformed(evt);
            }
        });
        jPanel1.add(txt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 93, -1));

        txt6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt6ActionPerformed(evt);
            }
        });
        jPanel1.add(txt6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 93, -1));

        txt7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(txt7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 93, -1));

        jtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Price", "Qty", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 70, 330, 310));

        chk4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        chk4.setText("A4 Sheet");
        chk4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk4ActionPerformed(evt);
            }
        });
        jPanel1.add(chk4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 99, -1));

        txt4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(txt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 99, -1));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, -1, -1));

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setText("Pay");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 430, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Total Amount");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, 110, 50));

        txtbill.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtbill.setText("Total");
        jPanel1.add(txtbill, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 430, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_20230325_150809.jpg"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chk4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chk4ActionPerformed

    private void chk7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chk7ActionPerformed

    private void chk2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chk2ActionPerformed

    private void chk3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chk3ActionPerformed

    private void txt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt5ActionPerformed

    private void txt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         double sum = 0;
        double price;
        double qty;
        double cal = 0;
        
         if(chk1.isSelected())
        {
           String pencil = chk1.getText();
            price = 10.0;
            qty = Integer.parseInt(txt1.getText());
            {
                cal = (qty * price) ;
                model = (DefaultTableModel)jtable.getModel();
                model.addRow(new Object[]
                {  
                pencil,
                 price,
                 qty,
                 cal
                }); } 
        }
                if(chk2.isSelected())
        {
           String pen = chk2.getText();
            price = 10.0;
            qty = Integer.parseInt(txt2.getText());
            {
                cal = (qty * price) ;
                model = (DefaultTableModel)jtable.getModel();
                model.addRow(new Object[]
                {  
                pen,
                 price,
                 qty,
                 cal
                }); }
        }
                if(chk3.isSelected())
        {
           String eraser= chk3.getText();
            price = 5.0;
            qty = Integer.parseInt(txt3.getText());
            {
                cal = (qty * price) ;
                model = (DefaultTableModel)jtable.getModel();
                model.addRow(new Object[]
                {  
                eraser,
                 price,
                 qty,
                 cal
                }); }
        }
                if(chk4.isSelected())
        {
           String A4Sheet = chk4.getText();
            price = 2.0;
            qty = Integer.parseInt(txt4.getText());
            {
                cal = (qty * price) ;
                model = (DefaultTableModel)jtable.getModel();
                model.addRow(new Object[]
                {  
                A4Sheet,
                 price,
                 qty,
                 cal
                });  }
        }
                if(chk5.isSelected())
        {
           String Sharpner = chk5.getText();
            price = 5.0;
            qty = Integer.parseInt(txt5.getText());
            {
                cal = (qty * price) ;
                model = (DefaultTableModel)jtable.getModel();
                model.addRow(new Object[]
                {  
                Sharpner,
                 price,
                 qty,
                 cal
                });  }
        }
                if(chk6.isSelected())
        {
           String Chart = chk6.getText();
            price = 10.0;
            qty = Integer.parseInt(txt6.getText());
            {
                cal = (qty * price) ;
                model = (DefaultTableModel)jtable.getModel();
                model.addRow(new Object[]
                {  
                Chart,
                 price,
                 qty,
                 cal
                });  }
        }
                if(chk7.isSelected())
        {
           String Note= chk7.getText();
            price = 10.0;
            qty = Integer.parseInt(txt7.getText());
            {
                cal = (qty * price) ;
                model = (DefaultTableModel)jtable.getModel();
                model.addRow(new Object[]
                {  
                Note,
                 price,
                 qty,
                 cal
                });  
            }}
                 for(double i=0; i <jtable.getRowCount(); i++)
        {
            sum = sum + Double.parseDouble(jtable.getValueAt((int) i, 3).toString());
        }
        
        txtbill.setText(Double.toString(sum));
                   
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
               new Payment().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
        
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(stationary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(stationary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(stationary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(stationary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new stationary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chk1;
    private javax.swing.JCheckBox chk2;
    private javax.swing.JCheckBox chk3;
    private javax.swing.JCheckBox chk4;
    private javax.swing.JCheckBox chk5;
    private javax.swing.JCheckBox chk6;
    private javax.swing.JCheckBox chk7;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtable;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt3;
    private javax.swing.JTextField txt4;
    private javax.swing.JTextField txt5;
    private javax.swing.JTextField txt6;
    private javax.swing.JTextField txt7;
    private javax.swing.JLabel txtbill;
    // End of variables declaration//GEN-END:variables
}
